ALTER DEFAULT PRIVILEGES FOR ROLE shopkeet IN SCHEMA public
  REVOKE ALL ON TABLES FROM shopkeet_app;
ALTER DEFAULT PRIVILEGES FOR ROLE shopkeet IN SCHEMA public
  REVOKE ALL ON SEQUENCES FROM shopkeet_app;