global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: shopkeet-api
    metrics_path: /metrics
    bearer_token: dev-metrics-token
    static_configs:
      - targets: ["api:3001"]